- .gitignore
- .run/Run API Locally.run.xml
- README.md
- scripts/call-api-as-system-client.sh
Added a run config to run the API locally using .env
Added a script to call the API while automatically fetching a token using the UI client from kubectl
Updated run local instructions to match.
> PRC-37 - Small improvements to run locally

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/PrisonerContactSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerContactRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ReadOnlyRepository.kt
- src/main/resources/migrations/common/R__v_prisoner_contacts.sql
- src/main/resources/migrations/common/V2024.08.02.2__baseline_data.sql
- src/main/resources/migrations/common/V2024.08.19.1__reset_sequences.sql
This PR also:
* Adjusts sequences to account for  base data loading.
* Sets the primary flag for emails, phones and addresses.
* Adds a prisoner_contact relationship (for testing)
> PRC-42: Create contacts view

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/OpenApiConfiguration.kt
Creates an openApiConfiguration bean and sets authorization strategy.
> PRC-51: Adding swagger support

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/Contact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactByIdIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
Added an API to get contacts by id. This is mostly to support testing during the create journey at the moment. Integration to follow in another PR.
> PRC-52: API to get contact by id

- scripts/call-api-as-system-client.sh
- scripts/get-auth-token.sh
Split up the utility scripts so there's one just for getting the auth token which can be used with the swagger docs.
> PRC-52: Script to get token to use with swagger

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/TimeConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/ContactEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/IsOverEighteen.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/Contact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/main/resources/migrations/common/V2024.09.04.1__reset_sequences.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactByIdIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
Add support for entering an estimated date of birth (DOB) if the DOB is not known. Return the isOverEighteen flag by either
* Calculating it if there is a DOB
* Using the value supplied when creating the contact 
* Default to DO_NOT_KNOW
> PRC-58: Add is over eighteen to crete and get contact flow

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/ReferenceCodeEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ReferenceCodeMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/ReferenceCode.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ReferenceCodeRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ReferenceCodeController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ReferenceCodeService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/ReferenceCodesResourceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ReferenceCodeServiceTest.kt
Simple API to get by group code.
Lift and shift from BVLS with a few extra tests
> PRC-108: Add references code API

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ContactsServiceMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/AddContactRelationshipRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/ContactRelationship.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/AddContactRelationshipIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactWithRelationshipIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
API for linking contacts with a prisoner when the contact already exists.
> PRC-125: API for contact relationship

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactController.kt
Fix swagger document for contact search endpoint
> PRC-104 : Fix swagger document

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/ContactPhoneEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ContactPhoneEntityMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateContactPhoneRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/UpdateContactPhoneRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/ContactPhone.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactPhoneRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactPhoneSyncController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncContactPhoneService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SyncContactPhoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncContactPhoneServiceTest.kt
Changes : 
Added following operations for data sync from NOMIS into DPS contact_phone table
1) (Retrieve) GET /sync/contact-phone/{contactPhoneId): ContactPhone  
2) (Create) PUT /sync/contact-phone: ContactPhone { body: CreateContactPhoneRequest }
3) (Update) POST /sync/contact-phone/{contactPhoneId}: ContactPhone { body: UpdateContactPhoneRequest }
4) (Delete) DELETE /sync/contact-phone/{contactPhoneId)
> Create contact phone sync endpoints, service and repository methods

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/ContactIdentityEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ContactIdentityEntityMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateContactIdentityRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/UpdateContactIdentityRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/ContactIdentity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactIdentityRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactIdentitySyncController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncContactIdentityService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SyncContactIdentityIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncContactIdentityServiceTest.kt
Changes :
Create contact identity sync endpoints, service and repository methods
> Create contact identity sync endpoints, service and repository methods

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/ContactRestrictionEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ContactRestrictionEntityMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateContactRestrictionRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/UpdateContactRestrictionRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/ContactRestriction.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactRestrictionRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactRestrictionSyncController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncContactRestrictionService.kt
- src/main/resources/migrations/common/V2024.08.02.2__baseline_data.sql
- src/main/resources/migrations/common/V2024.08.19.1__reset_sequences.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SyncContactRestrictionIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncContactRestrictionServiceTest.kt
Changes :
Create contact restriction sync endpoints, service and repository methods
> Create contact restriction sync endpoints, service and repository methods

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/ContactSearchRequest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SearchContactsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/ContactSearchRequestTest.kt
PRC-46 : Allow entering hyphens and apostrophes for name for contact search
>  PRC-46 : Allow entering hyphens and apostrophes for name

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/ContactAddressDetailsEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ContactAddressDetailsMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ContactAddressMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ContactsServiceMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/ContactAddress.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/ContactAddressDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/GetContactResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactAddressDetailsRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncService.kt
- src/main/resources/migrations/common/R__v_contact_addresses.sql
- src/main/resources/migrations/common/V2024.08.02.2__baseline_data.sql
- src/main/resources/migrations/common/V2024.08.19.1__reset_sequences.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactByIdIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerContactsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SearchContactsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SyncEndpointsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ContactAddressDetailsMappersKtTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
Add all addresses for a contact to get contact endpoint.
> PRC-150: Add addresses to get contact

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/PrisonerContactEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/PrisonerContactEntityMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/CreatePrisonerContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/UpdatePrisonerContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/sync/PrisonerContact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerContactSyncController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncPrisonerContactService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SyncPrisonerContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncPrisonerContactServiceTest.kt
PRC-97 : API - prisoner contact sync endpoints, service, repository methods
> PRC-97 : API - prisoner contact sync endpoints, service, repository methods

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/PrisonerContactRestrictionEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/PrisonerContactRestrictionEntityMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/CreatePrisonerContactRestrictionRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/UpdatePrisonerContactRestrictionRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/sync/PrisonerContactRestriction.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerContactRestrictionRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerContactRestrictionSyncController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncPrisonerContactRestrictionService.kt
- src/main/resources/migrations/common/V2024.08.02.2__baseline_data.sql
- src/main/resources/migrations/common/V2024.08.19.1__reset_sequences.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SyncPrisonerContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SyncPrisonerContactRestrictionEntityIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncPrisonerContactRestrictionEntityServiceTest.kt
PRC-98 : API - prisoner contact restriction sync endpoints, service, repository methods
> PRC-98 : API - prisoner contact restriction sync endpoints, service, repository methods

- .circleci/config.yml
- helm_deploy/values-preprod.yaml
PRC-156 : Build the PREPROD environment
> PRC-156 : Build the PREPROD environment

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
PRC-15 : enable db auto clean until go live
> PRC-15 : enable db auto clean until go live

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/PatchContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchServiceTest.kt
PRC-203 : patch contact - domestic status
> PRC-203 : patch contact - domestic status

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/ContactEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/PatchContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/PatchContactResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/CreateContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/UpdateContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/sync/Contact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchServiceTest.kt
PRC-205 : patch contact - staff flag
> PRC-205 : patch contact - staff flag

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/PatchContactRequest.kt
Only updatedBy is actually required
> PRC-73: Fix required-ness in swagger for patch request

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/patch/PatchContactEntityMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/sync/ContactEntityMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/PatchContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/PatchContactResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/CreateContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/UpdateContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/GetContactResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/sync/Contact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncContactService.kt
- src/main/resources/migrations/common/V2024.08.02.2__baseline_data.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactByIdIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/patch/PatchContactEntityMappersKtTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncContactServiceTest.kt
PRC-204 : API - add isStaff to get contact by id endpoint
1) add isStaff into getContactResponse
2) refactor other fields to be consistant
> PRC-204 : API - add isStaff to get contact by id endpoint

- .trivyignore
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactAddressPhoneRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPhoneService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactPhoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPhoneServiceTest.kt
Also checking in the trivy that's been there for a week or more now...
> PRC-212: Fix deletion of phone number when it's linked to an address

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactIdentityFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactIdentityController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactIdentityService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactIdentityFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactIdentityIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactIdentityControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactIdentityServiceTest.kt
Also moved exception on get into the facade.
> PRC-214: Delete contact identity

- src/main/resources/migrations/common/R__v_prisoner_contacts.sql
This caused spring to blow up if you had more than one email.
> PRC-194: Limit contact list to one email

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncContactEmailService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncContactIdentityService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncContactPhoneService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacadeTest.kt
Getting the events and facade/service tests first.
I then have some integration tests to extend and check domain events using stub events (to follow)
> PRC-310: Adding sync-triggered domain events (source NOMIS) for phones, emails and identities

- .circleci/config.yml
Send alerts and releases to our dev channel. May be moved to another channel later.
> PRC-187: Change to dev slack channel

- src/main/resources/migrations/common/R__v_prisoner_contacts.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerContactsIntegrationTest.kt
PRC-336 : Tech - Limit the UI display to SOCIAL contacts only
> PRC-336 : Tech - Limit the UI display to SOCIAL contacts only

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/UpdateRelationshipRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/PrisonerContactRelationshipDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactRelationshipService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/helpers/Examples.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerContactsRelationshipIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactRelationshipIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerContactControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactRelationshipServiceTest.kt
PRC-101 : manage contact approval flag
> PRC-101 : manage contact approval flag

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactAddressIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactAddressIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressServiceTest.kt
PRC-345 : Tech ticket - validate city, county & country codes in create/update address
> PRC-345 : Tech ticket - validate city, county & country codes in create/update address

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/client/prisonersearch/Prisoner.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/PrisonerContactSummaryEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/LinkedPrisonerDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/LinkedPrisonerRelationshipDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerContactSummaryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactLinkedPrisonersController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/LinkedPrisonersService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactService.kt
- src/main/resources/migrations/common/R__v_prisoner_contacts.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/client/prisonersearch/PrisonerSearchClientTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/helpers/Examples.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactLinkedPrisonerIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/wiremock/PrisonerSearchApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactLinkedPrisonersControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/LinkedPrisonersServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactRelationshipServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactServiceTest.kt
API to get prisoners linked to a contact, this can return social and official contacts but the other uses of v_prisoner_contacts are still limited to Social only.
> PRC-140: Linked prisoners API

- helm_deploy/hmpps-contacts-api/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
Just aligning helm namespace secrets in all envs.
> PRC-47: update namespace secrets

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncContactAddressPhoneService.kt
Reorder deletes to match the way this is done in the non-sync service.
> PRC-366: Ordering of deletes for sync contact address phone

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/RestrictionsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncContactRestrictionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactRestrictionIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/RestrictionsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncContactRestrictionServiceTest.kt
PRC-355 : Global restrictions - can add with an expiry data before the start date on DPS.
> PRC-355 : Global restrictions - can add with an expiry data before the start date on DPS.

- .trivyignore
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/EnumMapperConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/HmppsContactsApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/ReferenceCodeEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/exception/InvalidReferenceCodeGroupException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ReferenceCodeGroupEnumConverter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/ReferenceCodeGroup.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/ReferenceCode.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ReferenceCodeRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ReferenceCodeController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressPhoneService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactIdentityService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPhoneService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ReferenceCodeService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/RestrictionsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/ReferenceCodesResourceIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ReferenceCodeGroupEnumConverterTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ReferenceCodeControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressPhoneServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactIdentityServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPhoneServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ReferenceCodeServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/RestrictionsServiceTest.kt
Also return 400 for an invalid group code instead of an empty list.
> PRC-386: Make reference code group an enum

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/sync/PrisonerContactEntityMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/SyncCreatePrisonerContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/SyncUpdatePrisonerContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/sync/SyncPrisonerContact.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerContactService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerContactServiceTest.kt
PRC-384 : Remove unnecessary fields from sync requests/responses
> PRC-384 : Remove unnecessary fields from sync requests/responses

- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactAddressPhoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactEmailIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactIdentityIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactPhoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactRestrictionIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactWithRelationshipIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreatePrisonerContactRestrictionIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactAddressPhoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactRelationshipIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactRestrictionIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdatePrisonerContactRestrictionIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactAddressIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactEmailIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactIdentityIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactPhoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactRestrictionIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerContactRestrictionEntityIntegrationTest.kt
- src/test/resources/application-test.yml
PRC-385 : Verify sync events are raised within some integration tests
> me integration tests

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/OrganisationFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateOrganisationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/OrganisationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/OrganisationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsService.kt
- src/main/resources/migrations/test/V2025.01.16.6__example_data.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/OrganisationFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/OrganisationIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/OrganisationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/OrganisationServiceTest.kt
> PRC-401 : Create organisation

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationSummaryEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/OrganisationFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ContactsServiceMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/OrganisationSummaryEntityMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/OrganisationSearchRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/OrganisationSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/OrganisationSummaryResultItemPage.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/SQLPredicates.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/OrganisationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/OrganisationService.kt
- src/main/resources/migrations/common/R__v_contact_addresses.sql
- src/main/resources/migrations/common/R__v_contacts_with_primary_address.sql
- src/main/resources/migrations/common/R__v_organisation_summary.sql
- src/main/resources/migrations/common/R__v_prisoner_contacts.sql
- src/main/resources/migrations/common/V2025.01.22.14__add_gin_index_on_corporates.sql
- src/main/resources/migrations/common/V2025.01.23.15__fix_county_ref_data.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/OrganisationSearchIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/OrganisationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/OrganisationServiceTest.kt
Basic search function for organisations which returns a list of summary objects.
Also fixed issue with contact address views using the wrong reference data and some additional padding that was in county reference data.
> PRC-271: Organisation summary and search

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/EmploymentFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateEmploymentRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/UpdateEmploymentRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactEmploymentController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/EmploymentService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/EmploymentFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateEmploymentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteEmploymentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetEmploymentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchEmploymentsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateEmploymentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/EmploymentServiceTest.kt
Includes relevant sync events.
> PRC-181: Employments CRUD API

- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/SecureAPIIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateEmploymentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteEmploymentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetEmploymentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchEmploymentsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateEmploymentIntegrationTest.kt
Created SecureAPIIntegrationTestBase for integration tests for secure APIs. Runs standard checks that the user is authenticated and the tokens are valid and makes the developer provide a list of roles which apply.
> PRC-443: Common base tests for secure API
