run-local.sh
src/main/resources/migrations/common/V2024.08.02.1__baseline_tables.sql
src/main/resources/migrations/common/V2024.08.02.2__baseline_data.sql

* Postgres tables for the first pass at a new data model for review/discussion
* I've left out the official contact tables - employments and references to organisations.
* I've included some base data
** When this is merged, we'll need to drop the current table and flyway_schema_history table to let it recreate these objects and data **

PRC-7: First cut of new data model

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/HmppsContactsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/ContactEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/CreateContactRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerContactsController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
src/main/resources/application.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/ContactEntityControllerResourceIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactEntityControllerSummaryServiceTest.kt
src/test/resources/application-test.yml
src/test/resources/migrations/test/V2024.08.02.3__reset_identities_for_baseline_data_on_h2.sql

The most basic create contact API endpoint to get us going for now. Currently has no validation which will be added in subsequent PR.

PRC-52: Add basic create contact API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/HmppsContactsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateContactRequest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactIntegrationTest.kt

Added field length constraints with custom error messages to 1) be helpful to client and 2) stop exposing SQL error messages if the fields are too long.

PRC-52: Add validation to create contact

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/PrisonerContactEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/PrisonerContactMappers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/ContactRelationshipRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateContactRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerContactRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerContactSummaryRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactWithRelationshipIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SearchPrisonerContactsIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactServiceTest.kt

Added an optional relationship to the create contact request. This populates the prisoner_contact table and the contact will then be returned from the /prisoner/A1234BC/contact endpoint.

PRC-55: Add contact relationship to create contact

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/ContactEmailEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ContactEmailEntityMappers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateContactEmailRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/UpdateContactEmailRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/ContactEmail.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactEmailRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactEmailSyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncContactEmailService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SyncContactEmailIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncContactEmailServiceTest.kt

Changes :
Added following operations for data sync from NOMIS into DPS contact_email table
1) (Retrieve) GET /sync/contact-email{contactEmailId): ContactEmail  
2) (Create) PUT /sync/contact-email: ContactEmail { body: CreateContactEmailRequest }
3) (Update) POST /sync/contact-email/{contactEmailId}: ContactPhone { body: UpdateContactEmailRequest }
4) ames(Delete) DELETE /sync/contact-email/{contactEmailId)

Create contact email sync endpoints, service and repository methods #34

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/ContactEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ContactsServiceMappers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/GetContactResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
src/main/resources/migrations/common/V2024.08.02.2__baseline_data.sql
src/main/resources/migrations/common/V2024.08.19.1__reset_sequences.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/AddContactRelationshipIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactByIdIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SyncContactEmailIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SyncContactIdentityIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SyncContactPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SyncContactRestrictionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SyncEndpointsIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncContactEmailServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncContactIdentityServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncContactPhoneServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncContactRestrictionServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/SyncServiceTest.kt

This is to support the contact confirmation page and anything else needing the full details of the contact.

PRC-150: Add is deceased flag and deceased date to get contact

---

helm_deploy/values-dev.yaml
src/main/resources/application-auto-db-clean.yaml

This should stop us having to manually clean the DB when the migrations change.
Only applied in DEV for now.

PRC-173: Automatically clean and recreate the DB on changes applied

---

.trivyignore
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/EventConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactPhoneFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactPhoneController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/HmppsQueueOutboundEventsPublisher.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsPublisher.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactPhoneFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/StubOutboundEventsPublisher.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/TestConfiguration.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactPhoneControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsServiceTest.kt
src/test/resources/application-test.yml

Added events on creating, updating or deleting a contact phone.
Added a stub events service so that we can test without needing to use localstack/SQS/SNS.

PRC-226: Events on contact phone create, update and delete

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/PatchContactRequest.kt

Override the types so that we don't get JsonNullable automatically mapped

PRC-73: Fix types in swagger for patch request

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/patch/PatchContactRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/patch/ContactPatchFacade.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/patch/ContactPatchFacadeTest.kt
src/test/resources/application-test.yml

Also fixed the event being generated as it was prisoner contact (the relationship) instead of contact.

PRC-99: Add PATCH support for title and middleNames

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEvents.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/AddContactRelationshipIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactIntegrationTest.kt
src/test/resources/application-test.yml

Its to do with data classes inheriting from a parent class, and the parent class attributes not being visible to the ObjectMapper.

PRC-310: Fix (attempted) for missing source on events

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactAddressFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/CreateAddressResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/UpdateAddressResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactAddressRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactAddressFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactAddressIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactAddressIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactAddressIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressServiceTest.kt

Changed the create and update APIs for contact addresses to remove the primary and mail flags from other addresses if setting them on the subject. Also generates updated events for any other addresses updated.

PRC-323: Only allow primary and mail on one address

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/OpenApiConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/CityController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactAddressController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactAddressPhoneController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactEmailController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactGlobalRestrictionController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactIdentityController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactPhoneController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/CountryController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/CountyController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/LanguageController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerContactController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ReferenceCodeController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/migrate/MigrateContactController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/ContactAddressPhoneSyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/ContactAddressSyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/ContactEmailSyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/ContactIdentitySyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/ContactPhoneSyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/ContactRestrictionSyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/ContactSyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/PrisonerContactRestrictionSyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/PrisonerContactSyncController.kt

Sort into Contacts, Prisoner Contact Relationships, Restrictions and Reference Data in that order with Sync and Migrate endpoints last.
Also added the server URLs to allow switching for testing and a good way of publicly documenting the URLs.

PRC-349: Re-organise swagger docs

---

run-local.sh
src/main/resources/application-auto-db-clean.yaml
src/main/resources/migrations/common/R__v_contact_addresses.sql
src/main/resources/migrations/common/R__v_contact_identities.sql
src/main/resources/migrations/common/R__v_contact_phone_numbers.sql
src/main/resources/migrations/common/R__v_contact_restriction_details.sql
src/main/resources/migrations/common/R__v_contacts_with_primary_address.sql
src/main/resources/migrations/common/R__v_prisoner_contact_restriction_details.sql
src/main/resources/migrations/common/R__v_prisoner_contacts.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/PostgresIntegrationTestBase.kt

Drop views before creating them rather than using CREATE OR REPLACE. This allows re-name and re-order of columns which does not work with CREATE OR REPLACE. These migrations are only re-run if the checksum changes.

PRC-140: Fix migrations

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactAddressPhoneFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEvents.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactAddressFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactAddressPhoneFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactEmailFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactGlobalRestrictionsFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactIdentityFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactPhoneFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/PrisonerContactRestrictionsFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactAddressPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactAddressPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactAddressPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/patch/ContactFacadeTest.kt

For contact address phones, and in particular the delete operations, Syscon are unable to retrieve the row by ID after it has been deleted, so need a second ID (the contactAddressId) to work with.

PRC-365: Add additional event id into contact address phones

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactAddressFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/PatchContactAddressRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactAddressController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactAddressFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/helpers/Examples.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactAddressIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressServiceTest.kt

The manage address journeys should be individual “bounce” pages so it would be better to have a PATCH API that allows us to update only the relevant fields to each page (type, address lines, meta data).

PRC-348 : Tech ticket - Add PATCH API for address

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/ReferenceCodeGroup.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressPhoneService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactIdentityService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPhoneService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ReferenceCodeService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/RestrictionsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactIdentityIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactWithRelationshipIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/ReferenceCodesResourceIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactIdentityIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressPhoneServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactIdentityServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPatchServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPhoneServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ReferenceCodeServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/RestrictionsServiceTest.kt

Added missing validation for relationship type on creating contact.
Fixed issues with updating types when the reference code is no longer active (should be allowed).
Fixed issue with deleting phone number if the reference code for phone type was no longer active.

PRC-387: Standardise validation of reference codes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/BaseOrganisationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/EmploymentEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationAddressEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationAddressPhoneEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationEmailEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationPhoneEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationTypeEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationWebAddressEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationWithFixedIdEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/EmploymentRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationAddressPhoneRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationAddressRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationEmailRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationPhoneRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationTypeRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationWebAddressRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationWithFixedIdRepository.kt
src/main/resources/migrations/common/V2025.01.13.7__org_cleanup.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/db/OrganisationEntityIntegrationTest.kt

Includes some clean up of the data model:
* Rename organisation_web_address pk to organisation_web_address_id
* Remove contact_person_name from organisation as it's unused
* Remove constraints on employment table as this allows us to migrate contacts and organisations in any order. This was agreed with syscon for migration purposes.

PRC-405: Entities for organisations

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactByIdIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt

We were formerly including all address-specific numbers as well.
Address specific numbers are now only displayed and managed via editing the address they are associated with.

PRC-403: Only return global phone numbers in the phoneNumbers list for a contact.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/BaseOrganisationEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationAddressEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationAddressPhoneEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationEmailEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationPhoneEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationTypeEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/OrganisationWebAddressEntity.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/migrate/AbstractAuditable.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/migrate/MigrateContactRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/migrate/MigrateOrganisationRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/migrate/ElementType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/migrate/IdPair.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/migrate/MigrateContactResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/migrate/MigrateOrganisationResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/migrate/MigrateOrganisationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/migrate/ContactMigrationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/migrate/OrganisationMigrationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/migrate/MigrateOrganisationIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/migrate/ContactMigrationServiceTest.kt

Allow creation of an organisation using the NOMIS corporate id as the PK.
Allows for creation of all associated entities with it.
Currently does not handle duplicate migrations.
Remove use of @CreationTimestamp on organisation entities as this did not allow for overriding of the timestamp with one from NOMIS.

PRC-408: Initial migration endpoint for organisations

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/migrate/MigrateContactRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/SyncCreatePrisonerContactRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/SyncUpdatePrisonerContactRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/LinkedPrisonerRelationshipDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/PrisonerContactRelationshipDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/PrisonerContactSummary.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/sync/SyncPrisonerContact.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/EmploymentRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationAddressPhoneRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationAddressRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationEmailRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationPhoneRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationTypeRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/OrganisationWebAddressRepository.kt
src/main/resources/migrations/common/V2025.01.21.13__reference_data_updates.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/helpers/Examples.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactLinkedPrisonerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerContactRestrictionsIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerContactsRelationshipIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactLinkedPrisonersControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerContactControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/LinkedPrisonersServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactRelationshipServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactServiceTest.kt

A few reference data updates as requested by UCD team. Social contact types are now only referred to as Social instead of Social/Family and restriction descriptions case was normalised.
Also snuck in a tidy up of incorrect alias letters.

PRC-422: Fixup ref data

---

README.md
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/CityController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/CountryController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/CountyController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/LanguageController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt

This PR
* Replaces the use of language reference service calls in the contacts service with the common reference codes service.
* Deprecates the unused reference endpoints and services for CITY, COUNTY, COUNTRY and LANGUAGE.
* Adds the reasons for not using these data sets into the README file.

PRC-356: Deprecating the LANGUAGE, CITY, COUNTY, COUNTRY reference endpoints and service calls.

---

src/main/resources/migrations/common/R__v_contact_addresses.sql
src/main/resources/migrations/common/R__v_contact_identities.sql
src/main/resources/migrations/common/R__v_contact_phone_numbers.sql
src/main/resources/migrations/common/R__v_contact_restriction_details.sql
src/main/resources/migrations/common/R__v_contacts_with_primary_address.sql
src/main/resources/migrations/common/R__v_organisation_addresses.sql
src/main/resources/migrations/common/R__v_organisation_phone_numbers.sql
src/main/resources/migrations/common/R__v_organisation_summary.sql
src/main/resources/migrations/common/R__v_organisation_types.sql
src/main/resources/migrations/common/R__v_prisoner_contact_restriction_details.sql
src/main/resources/migrations/common/R__v_prisoner_contacts.sql
src/main/resources/migrations/common/V2025.01.24.16__alter_type_of_contact_and_org_pk_data.sql

The type of organisation and contact ids was updated which invalidates all the views but without requiring a change to the view.
Drop all the views in the faulty migration and trigger a recreation by altering the view files to force a checksum mismatch. :fingersxd:

PRC-181: Fix migrations

---

src/main/resources/migrations/test/V2025.01.24.16__alter_type_of_contact_and_org_pk_data.sql

Moving alter type of contact and organisation to only for tests to support random long. Will roll up scripts when we split the db between contacts and organisations.

PRC-181: Fix migrations part 2
